apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-dep
  name: my-dep
spec:
  replicas: {{ .Values.web.replicaCount | int }}
  selector:
    matchLabels:
      app: my-dep
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-dep
    spec:
      containers:
      - image: {{ include "web-image-url" .}}
        name: alation-web-n9fbk
        ports:
        - containerPort: 5000
        resources: {}
status: {}
